"""Test double for the LLM protocol."""

import re
from collections.abc import AsyncGenerator

from src.domain.ports.llm import LLM

_FALLBACK_RESPONSE = "I don't have enough information to answer this question."


class TestLLM(LLM):
    """Deterministic LLM test double.

    Returns a pre-configured canned response regardless of the prompt,
    making it suitable for testing code that depends on LLM output
    without running a real model.
    """

    def __init__(self, response: str = "This is a test response generated by the test LLM for testing purposes.") -> None:  # noqa: E501
        """Initialise the test LLM.

        Parameters
        ----------
        response : str
            The canned response returned by every call.
        """
        self._response = response

    async def generate(self, prompt: str, max_tokens: int = 600, temperature: float = 0.7) -> str:
        """Return the canned response, ignoring all parameters."""
        return self._response

    async def generate_stream(
        self,
        prompt: str,
        max_tokens: int = 600,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """Yield the canned response once."""
        yield self._response

    def get_model_name(self) -> str:
        return "test-llm"


class RealisticTestLLM(LLM):
    """LLM double that responds with actual document content from the prompt.

    Parses the prompt for ``[Source N]: ...`` sections and returns a response
    containing text from the first source, simulating realistic RAG behavior
    without loading a real model.
    """

    @staticmethod
    def _extract_source_texts(prompt: str) -> list[str]:
        """Extract source text from ``[Source N]: <content>`` lines in the prompt.

        Parameters
        ----------
        prompt : str
            The prompt string containing ``[Source N]:`` sections.

        Returns
        -------
        list[str]
            A list of source content strings in the order they appear.
        """
        # Handle both formats:
        #   [Source N]: <content>     (PDF pipeline — build_prompt)
        #   [Source N] <extra>...     (API docs pipeline — _generate_answer)
        matches = re.findall(r'\[Source \d+\]:?\s*(.+?)(?=\n\[Source \d+\]:?|\n\n|\Z)', prompt, re.DOTALL)  # noqa: E501
        return [m.strip() for m in matches]

    async def generate(self, prompt: str, max_tokens: int = 600, temperature: float = 0.7) -> str:
        """Return a response containing the first source text from the prompt.

        Uses :meth:`_extract_source_texts` to find ``[Source N]:`` sections.
        """
        sources = self._extract_source_texts(prompt)
        if not sources:
            return _FALLBACK_RESPONSE
        return f"Based on the provided material: {sources[0][:200]}"

    async def generate_stream(
        self,
        prompt: str,
        max_tokens: int = 600,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """Yield the result of :meth:`generate` once."""
        yield await self.generate(prompt, max_tokens, temperature)

    def get_model_name(self) -> str:
        return "realistic-test-llm"
