"""Test double for the LLM protocol."""

from collections.abc import AsyncGenerator

from src.domain.ports.llm import LLM


class TestLLM(LLM):
    """Deterministic LLM test double.

    Returns a pre-configured canned response regardless of the prompt,
    making it suitable for testing code that depends on LLM output
    without running a real model.
    """

    def __init__(self, response: str = "This is a test response generated by the test LLM for testing purposes.") -> None:  # noqa: E501
        """Initialise the test LLM.

        Parameters
        ----------
        response : str
            The canned response returned by every call.
        """
        self._response = response

    async def generate(self, prompt: str, max_tokens: int = 600, temperature: float = 0.7) -> str:
        """Return the canned response, ignoring all parameters."""
        return self._response

    async def generate_stream(
        self,
        prompt: str,
        max_tokens: int = 600,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """Yield the canned response once."""
        yield self._response

    def get_model_name(self) -> str:
        return "test-llm"
